on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: "14"
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - uses: actions/checkout@v2

      - run: make install

      - name: Handle weird Windows agent fixes
        if: runner.os == 'Windows'
        run: |
          ls ./web
          rm -Force ./web/browserslist.ps1
          rm -Force ./web/browserslist.cmd
          rm -Force ./web/browserslist

      - run: make build
